#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# skip if in CI. https://typicode.github.io/husky/guide.html#with-env-variables
[ -n "$CI" ] && exit 0

npm run test run
npm run test:e2e

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "master" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi