name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  clean_code:
    name: Lint and format code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Install packages
        run: npm ci

      - name: Format with Prettier
        run: npm run format

      - name: Lint with eslint
        run: npm run lint
